name = "linkedin-newsletter-rss"
main = "index.js"
compatibility_date = "2023-11-09"
workers_dev = true
node_compat = true

route = { pattern = "linkedinrss.humdiet.com/*", zone_name = "humdiet.com" }
